apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: shipbot
version: 0.1.0
dependencies:
- name: postgresql
  version: 9.4.1
  repository: https://charts.bitnami.com/bitnami