/* 
 * Argo
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace AutoDeploy.ArgoSupport.Workflows.Model
{
    /// <summary>
    /// ArgoArtifactRepositoryRef
    /// </summary>
    [DataContract]
    public partial class ArgoArtifactRepositoryRef :  IEquatable<ArgoArtifactRepositoryRef>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ArgoArtifactRepositoryRef" /> class.
        /// </summary>
        /// <param name="configMap">configMap.</param>
        /// <param name="key">key.</param>
        public ArgoArtifactRepositoryRef(string configMap = default(string), string key = default(string))
        {
            this.ConfigMap = configMap;
            this.Key = key;
        }
        
        /// <summary>
        /// Gets or Sets ConfigMap
        /// </summary>
        [DataMember(Name="configMap", EmitDefaultValue=false)]
        public string ConfigMap { get; set; }

        /// <summary>
        /// Gets or Sets Key
        /// </summary>
        [DataMember(Name="key", EmitDefaultValue=false)]
        public string Key { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ArgoArtifactRepositoryRef {\n");
            sb.Append("  ConfigMap: ").Append(ConfigMap).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ArgoArtifactRepositoryRef);
        }

        /// <summary>
        /// Returns true if ArgoArtifactRepositoryRef instances are equal
        /// </summary>
        /// <param name="input">Instance of ArgoArtifactRepositoryRef to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ArgoArtifactRepositoryRef input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ConfigMap == input.ConfigMap ||
                    (this.ConfigMap != null &&
                    this.ConfigMap.Equals(input.ConfigMap))
                ) && 
                (
                    this.Key == input.Key ||
                    (this.Key != null &&
                    this.Key.Equals(input.Key))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ConfigMap != null)
                    hashCode = hashCode * 59 + this.ConfigMap.GetHashCode();
                if (this.Key != null)
                    hashCode = hashCode * 59 + this.Key.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
