/* 
 * Argo
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace AutoDeploy.ArgoSupport.Workflows.Model
{
    /// <summary>
    /// ArtifactoryArtifact is the location of an artifactory artifact
    /// </summary>
    [DataContract]
    public partial class ArgoArtifactoryArtifact :  IEquatable<ArgoArtifactoryArtifact>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ArgoArtifactoryArtifact" /> class.
        /// </summary>
        [JsonConstructor]
        protected ArgoArtifactoryArtifact() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ArgoArtifactoryArtifact" /> class.
        /// </summary>
        /// <param name="passwordSecret">PasswordSecret is the secret selector to the repository password.</param>
        /// <param name="url">URL of the artifact (required).</param>
        /// <param name="usernameSecret">UsernameSecret is the secret selector to the repository username.</param>
        public ArgoArtifactoryArtifact(k8s.Models.V1SecretKeySelector passwordSecret = default(k8s.Models.V1SecretKeySelector), string url = default(string), k8s.Models.V1SecretKeySelector usernameSecret = default(k8s.Models.V1SecretKeySelector))
        {
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new InvalidDataException("url is a required property for ArgoArtifactoryArtifact and cannot be null");
            }
            else
            {
                this.Url = url;
            }
            this.PasswordSecret = passwordSecret;
            this.UsernameSecret = usernameSecret;
        }
        
        /// <summary>
        /// PasswordSecret is the secret selector to the repository password
        /// </summary>
        /// <value>PasswordSecret is the secret selector to the repository password</value>
        [DataMember(Name="passwordSecret", EmitDefaultValue=false)]
        public k8s.Models.V1SecretKeySelector PasswordSecret { get; set; }

        /// <summary>
        /// URL of the artifact
        /// </summary>
        /// <value>URL of the artifact</value>
        [DataMember(Name="url", EmitDefaultValue=false)]
        public string Url { get; set; }

        /// <summary>
        /// UsernameSecret is the secret selector to the repository username
        /// </summary>
        /// <value>UsernameSecret is the secret selector to the repository username</value>
        [DataMember(Name="usernameSecret", EmitDefaultValue=false)]
        public k8s.Models.V1SecretKeySelector UsernameSecret { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ArgoArtifactoryArtifact {\n");
            sb.Append("  PasswordSecret: ").Append(PasswordSecret).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  UsernameSecret: ").Append(UsernameSecret).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ArgoArtifactoryArtifact);
        }

        /// <summary>
        /// Returns true if ArgoArtifactoryArtifact instances are equal
        /// </summary>
        /// <param name="input">Instance of ArgoArtifactoryArtifact to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ArgoArtifactoryArtifact input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PasswordSecret == input.PasswordSecret ||
                    (this.PasswordSecret != null &&
                    this.PasswordSecret.Equals(input.PasswordSecret))
                ) && 
                (
                    this.Url == input.Url ||
                    (this.Url != null &&
                    this.Url.Equals(input.Url))
                ) && 
                (
                    this.UsernameSecret == input.UsernameSecret ||
                    (this.UsernameSecret != null &&
                    this.UsernameSecret.Equals(input.UsernameSecret))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PasswordSecret != null)
                    hashCode = hashCode * 59 + this.PasswordSecret.GetHashCode();
                if (this.Url != null)
                    hashCode = hashCode * 59 + this.Url.GetHashCode();
                if (this.UsernameSecret != null)
                    hashCode = hashCode * 59 + this.UsernameSecret.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
