/* 
 * Argo
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace AutoDeploy.ArgoSupport.Workflows.Model
{
    /// <summary>
    /// Outputs hold parameters, artifacts, and results from a step
    /// </summary>
    [DataContract]
    public partial class ArgoOutputs :  IEquatable<ArgoOutputs>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ArgoOutputs" /> class.
        /// </summary>
        /// <param name="artifacts">Artifacts holds the list of output artifacts produced by a step.</param>
        /// <param name="parameters">Parameters holds the list of output parameters produced by a step.</param>
        /// <param name="result">Result holds the result (stdout) of a script template.</param>
        public ArgoOutputs(List<ArgoArtifact> artifacts = default(List<ArgoArtifact>), List<ArgoParameter> parameters = default(List<ArgoParameter>), string result = default(string))
        {
            this.Artifacts = artifacts;
            this.Parameters = parameters;
            this.Result = result;
        }
        
        /// <summary>
        /// Artifacts holds the list of output artifacts produced by a step
        /// </summary>
        /// <value>Artifacts holds the list of output artifacts produced by a step</value>
        [DataMember(Name="artifacts", EmitDefaultValue=false)]
        public List<ArgoArtifact> Artifacts { get; set; }

        /// <summary>
        /// Parameters holds the list of output parameters produced by a step
        /// </summary>
        /// <value>Parameters holds the list of output parameters produced by a step</value>
        [DataMember(Name="parameters", EmitDefaultValue=false)]
        public List<ArgoParameter> Parameters { get; set; }

        /// <summary>
        /// Result holds the result (stdout) of a script template
        /// </summary>
        /// <value>Result holds the result (stdout) of a script template</value>
        [DataMember(Name="result", EmitDefaultValue=false)]
        public string Result { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ArgoOutputs {\n");
            sb.Append("  Artifacts: ").Append(Artifacts).Append("\n");
            sb.Append("  Parameters: ").Append(Parameters).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ArgoOutputs);
        }

        /// <summary>
        /// Returns true if ArgoOutputs instances are equal
        /// </summary>
        /// <param name="input">Instance of ArgoOutputs to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ArgoOutputs input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Artifacts == input.Artifacts ||
                    this.Artifacts != null &&
                    this.Artifacts.SequenceEqual(input.Artifacts)
                ) && 
                (
                    this.Parameters == input.Parameters ||
                    this.Parameters != null &&
                    this.Parameters.SequenceEqual(input.Parameters)
                ) && 
                (
                    this.Result == input.Result ||
                    (this.Result != null &&
                    this.Result.Equals(input.Result))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Artifacts != null)
                    hashCode = hashCode * 59 + this.Artifacts.GetHashCode();
                if (this.Parameters != null)
                    hashCode = hashCode * 59 + this.Parameters.GetHashCode();
                if (this.Result != null)
                    hashCode = hashCode * 59 + this.Result.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
