/* 
 * Argo
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace AutoDeploy.ArgoSupport.Workflows.Model
{
    /// <summary>
    /// ScriptTemplate is a template subtype to enable scripting through code steps
    /// </summary>
    [DataContract]
    public partial class ArgoScriptTemplate :  IEquatable<ArgoScriptTemplate>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ArgoScriptTemplate" /> class.
        /// </summary>
        [JsonConstructor]
        protected ArgoScriptTemplate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ArgoScriptTemplate" /> class.
        /// </summary>
        /// <param name="args">Arguments to the entrypoint. The docker image&#39;s CMD is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container&#39;s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell.</param>
        /// <param name="command">Entrypoint array. Not executed within a shell. The docker image&#39;s ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container&#39;s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell.</param>
        /// <param name="env">List of environment variables to set in the container. Cannot be updated..</param>
        /// <param name="envFrom">List of sources to populate environment variables in the container. The keys defined within a source must be a C_IDENTIFIER. All invalid keys will be reported as an event when the container is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence. Cannot be updated..</param>
        /// <param name="image">Docker image name. More info: https://kubernetes.io/docs/concepts/containers/images This field is optional to allow higher level config management to default or override container images in workload controllers like Deployments and StatefulSets..</param>
        /// <param name="imagePullPolicy">Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images.</param>
        /// <param name="lifecycle">Actions that the management system should take in response to container lifecycle events. Cannot be updated..</param>
        /// <param name="livenessProbe">Periodic probe of container liveness. Container will be restarted if the probe fails. Cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes.</param>
        /// <param name="name">Name of the container specified as a DNS_LABEL. Each container in a pod must have a unique name (DNS_LABEL). Cannot be updated. (required).</param>
        /// <param name="ports">List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default \&quot;0.0.0.0\&quot; address inside a container will be accessible from the network. Cannot be updated..</param>
        /// <param name="readinessProbe">Periodic probe of container service readiness. Container will be removed from service endpoints if the probe fails. Cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes.</param>
        /// <param name="resources">Compute Resources required by this container. Cannot be updated. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/.</param>
        /// <param name="securityContext">Security options the pod should run with. More info: https://kubernetes.io/docs/concepts/policy/security-context/ More info: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/.</param>
        /// <param name="source">Source contains the source code of the script to execute (required).</param>
        /// <param name="stdin">Whether this container should allocate a buffer for stdin in the container runtime. If this is not set, reads from stdin in the container will always result in EOF. Default is false..</param>
        /// <param name="stdinOnce">Whether the container runtime should close the stdin channel after it has been opened by a single attach. When stdin is true the stdin stream will remain open across multiple attach sessions. If stdinOnce is set to true, stdin is opened on container start, is empty until the first client attaches to stdin, and then remains open and accepts data until the client disconnects, at which time stdin is closed and remains closed until the container is restarted. If this flag is false, a container processes that reads from stdin will never receive an EOF. Default is false.</param>
        /// <param name="terminationMessagePath">Optional: Path at which the file to which the container&#39;s termination message will be written is mounted into the container&#39;s filesystem. Message written is intended to be brief final status, such as an assertion failure message. Will be truncated by the node if greater than 4096 bytes. The total message length across all containers will be limited to 12kb. Defaults to /dev/termination-log. Cannot be updated..</param>
        /// <param name="terminationMessagePolicy">Indicate how the termination message should be populated. File will use the contents of terminationMessagePath to populate the container status message on both success and failure. FallbackToLogsOnError will use the last chunk of container log output if the termination message file is empty and the container exited with an error. The log output is limited to 2048 bytes or 80 lines, whichever is smaller. Defaults to File. Cannot be updated..</param>
        /// <param name="tty">Whether this container should allocate a TTY for itself, also requires &#39;stdin&#39; to be true. Default is false..</param>
        /// <param name="volumeDevices">volumeDevices is the list of block devices to be used by the container. This is a beta feature..</param>
        /// <param name="volumeMounts">Pod volumes to mount into the container&#39;s filesystem. Cannot be updated..</param>
        /// <param name="workingDir">Container&#39;s working directory. If not specified, the container runtime&#39;s default will be used, which might be configured in the container image. Cannot be updated..</param>
        public ArgoScriptTemplate(List<string> args = default(List<string>), List<string> command = default(List<string>), List<k8s.Models.V1EnvVar> env = default(List<k8s.Models.V1EnvVar>), List<k8s.Models.V1EnvFromSource> envFrom = default(List<k8s.Models.V1EnvFromSource>), string image = default(string), string imagePullPolicy = default(string), k8s.Models.V1Lifecycle lifecycle = default(k8s.Models.V1Lifecycle), k8s.Models.V1Probe livenessProbe = default(k8s.Models.V1Probe), string name = default(string), List<k8s.Models.V1ContainerPort> ports = default(List<k8s.Models.V1ContainerPort>), k8s.Models.V1Probe readinessProbe = default(k8s.Models.V1Probe), k8s.Models.V1ResourceRequirements resources = default(k8s.Models.V1ResourceRequirements), k8s.Models.V1SecurityContext securityContext = default(k8s.Models.V1SecurityContext), string source = default(string), bool? stdin = default(bool?), bool? stdinOnce = default(bool?), string terminationMessagePath = default(string), string terminationMessagePolicy = default(string), bool? tty = default(bool?), List<k8s.Models.V1VolumeDevice> volumeDevices = default(List<k8s.Models.V1VolumeDevice>), List<k8s.Models.V1VolumeMount> volumeMounts = default(List<k8s.Models.V1VolumeMount>), string workingDir = default(string))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for ArgoScriptTemplate and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "source" is required (not null)
            if (source == null)
            {
                throw new InvalidDataException("source is a required property for ArgoScriptTemplate and cannot be null");
            }
            else
            {
                this.Source = source;
            }
            this.Args = args;
            this.Command = command;
            this.Env = env;
            this.EnvFrom = envFrom;
            this.Image = image;
            this.ImagePullPolicy = imagePullPolicy;
            this.Lifecycle = lifecycle;
            this.LivenessProbe = livenessProbe;
            this.Ports = ports;
            this.ReadinessProbe = readinessProbe;
            this.Resources = resources;
            this.SecurityContext = securityContext;
            this.Stdin = stdin;
            this.StdinOnce = stdinOnce;
            this.TerminationMessagePath = terminationMessagePath;
            this.TerminationMessagePolicy = terminationMessagePolicy;
            this.Tty = tty;
            this.VolumeDevices = volumeDevices;
            this.VolumeMounts = volumeMounts;
            this.WorkingDir = workingDir;
        }
        
        /// <summary>
        /// Arguments to the entrypoint. The docker image&#39;s CMD is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container&#39;s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell
        /// </summary>
        /// <value>Arguments to the entrypoint. The docker image&#39;s CMD is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container&#39;s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell</value>
        [DataMember(Name="args", EmitDefaultValue=false)]
        public List<string> Args { get; set; }

        /// <summary>
        /// Entrypoint array. Not executed within a shell. The docker image&#39;s ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container&#39;s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell
        /// </summary>
        /// <value>Entrypoint array. Not executed within a shell. The docker image&#39;s ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container&#39;s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell</value>
        [DataMember(Name="command", EmitDefaultValue=false)]
        public List<string> Command { get; set; }

        /// <summary>
        /// List of environment variables to set in the container. Cannot be updated.
        /// </summary>
        /// <value>List of environment variables to set in the container. Cannot be updated.</value>
        [DataMember(Name="env", EmitDefaultValue=false)]
        public List<k8s.Models.V1EnvVar> Env { get; set; }

        /// <summary>
        /// List of sources to populate environment variables in the container. The keys defined within a source must be a C_IDENTIFIER. All invalid keys will be reported as an event when the container is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence. Cannot be updated.
        /// </summary>
        /// <value>List of sources to populate environment variables in the container. The keys defined within a source must be a C_IDENTIFIER. All invalid keys will be reported as an event when the container is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence. Cannot be updated.</value>
        [DataMember(Name="envFrom", EmitDefaultValue=false)]
        public List<k8s.Models.V1EnvFromSource> EnvFrom { get; set; }

        /// <summary>
        /// Docker image name. More info: https://kubernetes.io/docs/concepts/containers/images This field is optional to allow higher level config management to default or override container images in workload controllers like Deployments and StatefulSets.
        /// </summary>
        /// <value>Docker image name. More info: https://kubernetes.io/docs/concepts/containers/images This field is optional to allow higher level config management to default or override container images in workload controllers like Deployments and StatefulSets.</value>
        [DataMember(Name="image", EmitDefaultValue=false)]
        public string Image { get; set; }

        /// <summary>
        /// Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images
        /// </summary>
        /// <value>Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images</value>
        [DataMember(Name="imagePullPolicy", EmitDefaultValue=false)]
        public string ImagePullPolicy { get; set; }

        /// <summary>
        /// Actions that the management system should take in response to container lifecycle events. Cannot be updated.
        /// </summary>
        /// <value>Actions that the management system should take in response to container lifecycle events. Cannot be updated.</value>
        [DataMember(Name="lifecycle", EmitDefaultValue=false)]
        public k8s.Models.V1Lifecycle Lifecycle { get; set; }

        /// <summary>
        /// Periodic probe of container liveness. Container will be restarted if the probe fails. Cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
        /// </summary>
        /// <value>Periodic probe of container liveness. Container will be restarted if the probe fails. Cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes</value>
        [DataMember(Name="livenessProbe", EmitDefaultValue=false)]
        public k8s.Models.V1Probe LivenessProbe { get; set; }

        /// <summary>
        /// Name of the container specified as a DNS_LABEL. Each container in a pod must have a unique name (DNS_LABEL). Cannot be updated.
        /// </summary>
        /// <value>Name of the container specified as a DNS_LABEL. Each container in a pod must have a unique name (DNS_LABEL). Cannot be updated.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default \&quot;0.0.0.0\&quot; address inside a container will be accessible from the network. Cannot be updated.
        /// </summary>
        /// <value>List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default \&quot;0.0.0.0\&quot; address inside a container will be accessible from the network. Cannot be updated.</value>
        [DataMember(Name="ports", EmitDefaultValue=false)]
        public List<k8s.Models.V1ContainerPort> Ports { get; set; }

        /// <summary>
        /// Periodic probe of container service readiness. Container will be removed from service endpoints if the probe fails. Cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
        /// </summary>
        /// <value>Periodic probe of container service readiness. Container will be removed from service endpoints if the probe fails. Cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes</value>
        [DataMember(Name="readinessProbe", EmitDefaultValue=false)]
        public k8s.Models.V1Probe ReadinessProbe { get; set; }

        /// <summary>
        /// Compute Resources required by this container. Cannot be updated. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
        /// </summary>
        /// <value>Compute Resources required by this container. Cannot be updated. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/</value>
        [DataMember(Name="resources", EmitDefaultValue=false)]
        public k8s.Models.V1ResourceRequirements Resources { get; set; }

        /// <summary>
        /// Security options the pod should run with. More info: https://kubernetes.io/docs/concepts/policy/security-context/ More info: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
        /// </summary>
        /// <value>Security options the pod should run with. More info: https://kubernetes.io/docs/concepts/policy/security-context/ More info: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/</value>
        [DataMember(Name="securityContext", EmitDefaultValue=false)]
        public k8s.Models.V1SecurityContext SecurityContext { get; set; }

        /// <summary>
        /// Source contains the source code of the script to execute
        /// </summary>
        /// <value>Source contains the source code of the script to execute</value>
        [DataMember(Name="source", EmitDefaultValue=false)]
        public string Source { get; set; }

        /// <summary>
        /// Whether this container should allocate a buffer for stdin in the container runtime. If this is not set, reads from stdin in the container will always result in EOF. Default is false.
        /// </summary>
        /// <value>Whether this container should allocate a buffer for stdin in the container runtime. If this is not set, reads from stdin in the container will always result in EOF. Default is false.</value>
        [DataMember(Name="stdin", EmitDefaultValue=false)]
        public bool? Stdin { get; set; }

        /// <summary>
        /// Whether the container runtime should close the stdin channel after it has been opened by a single attach. When stdin is true the stdin stream will remain open across multiple attach sessions. If stdinOnce is set to true, stdin is opened on container start, is empty until the first client attaches to stdin, and then remains open and accepts data until the client disconnects, at which time stdin is closed and remains closed until the container is restarted. If this flag is false, a container processes that reads from stdin will never receive an EOF. Default is false
        /// </summary>
        /// <value>Whether the container runtime should close the stdin channel after it has been opened by a single attach. When stdin is true the stdin stream will remain open across multiple attach sessions. If stdinOnce is set to true, stdin is opened on container start, is empty until the first client attaches to stdin, and then remains open and accepts data until the client disconnects, at which time stdin is closed and remains closed until the container is restarted. If this flag is false, a container processes that reads from stdin will never receive an EOF. Default is false</value>
        [DataMember(Name="stdinOnce", EmitDefaultValue=false)]
        public bool? StdinOnce { get; set; }

        /// <summary>
        /// Optional: Path at which the file to which the container&#39;s termination message will be written is mounted into the container&#39;s filesystem. Message written is intended to be brief final status, such as an assertion failure message. Will be truncated by the node if greater than 4096 bytes. The total message length across all containers will be limited to 12kb. Defaults to /dev/termination-log. Cannot be updated.
        /// </summary>
        /// <value>Optional: Path at which the file to which the container&#39;s termination message will be written is mounted into the container&#39;s filesystem. Message written is intended to be brief final status, such as an assertion failure message. Will be truncated by the node if greater than 4096 bytes. The total message length across all containers will be limited to 12kb. Defaults to /dev/termination-log. Cannot be updated.</value>
        [DataMember(Name="terminationMessagePath", EmitDefaultValue=false)]
        public string TerminationMessagePath { get; set; }

        /// <summary>
        /// Indicate how the termination message should be populated. File will use the contents of terminationMessagePath to populate the container status message on both success and failure. FallbackToLogsOnError will use the last chunk of container log output if the termination message file is empty and the container exited with an error. The log output is limited to 2048 bytes or 80 lines, whichever is smaller. Defaults to File. Cannot be updated.
        /// </summary>
        /// <value>Indicate how the termination message should be populated. File will use the contents of terminationMessagePath to populate the container status message on both success and failure. FallbackToLogsOnError will use the last chunk of container log output if the termination message file is empty and the container exited with an error. The log output is limited to 2048 bytes or 80 lines, whichever is smaller. Defaults to File. Cannot be updated.</value>
        [DataMember(Name="terminationMessagePolicy", EmitDefaultValue=false)]
        public string TerminationMessagePolicy { get; set; }

        /// <summary>
        /// Whether this container should allocate a TTY for itself, also requires &#39;stdin&#39; to be true. Default is false.
        /// </summary>
        /// <value>Whether this container should allocate a TTY for itself, also requires &#39;stdin&#39; to be true. Default is false.</value>
        [DataMember(Name="tty", EmitDefaultValue=false)]
        public bool? Tty { get; set; }

        /// <summary>
        /// volumeDevices is the list of block devices to be used by the container. This is a beta feature.
        /// </summary>
        /// <value>volumeDevices is the list of block devices to be used by the container. This is a beta feature.</value>
        [DataMember(Name="volumeDevices", EmitDefaultValue=false)]
        public List<k8s.Models.V1VolumeDevice> VolumeDevices { get; set; }

        /// <summary>
        /// Pod volumes to mount into the container&#39;s filesystem. Cannot be updated.
        /// </summary>
        /// <value>Pod volumes to mount into the container&#39;s filesystem. Cannot be updated.</value>
        [DataMember(Name="volumeMounts", EmitDefaultValue=false)]
        public List<k8s.Models.V1VolumeMount> VolumeMounts { get; set; }

        /// <summary>
        /// Container&#39;s working directory. If not specified, the container runtime&#39;s default will be used, which might be configured in the container image. Cannot be updated.
        /// </summary>
        /// <value>Container&#39;s working directory. If not specified, the container runtime&#39;s default will be used, which might be configured in the container image. Cannot be updated.</value>
        [DataMember(Name="workingDir", EmitDefaultValue=false)]
        public string WorkingDir { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ArgoScriptTemplate {\n");
            sb.Append("  Args: ").Append(Args).Append("\n");
            sb.Append("  Command: ").Append(Command).Append("\n");
            sb.Append("  Env: ").Append(Env).Append("\n");
            sb.Append("  EnvFrom: ").Append(EnvFrom).Append("\n");
            sb.Append("  Image: ").Append(Image).Append("\n");
            sb.Append("  ImagePullPolicy: ").Append(ImagePullPolicy).Append("\n");
            sb.Append("  Lifecycle: ").Append(Lifecycle).Append("\n");
            sb.Append("  LivenessProbe: ").Append(LivenessProbe).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Ports: ").Append(Ports).Append("\n");
            sb.Append("  ReadinessProbe: ").Append(ReadinessProbe).Append("\n");
            sb.Append("  Resources: ").Append(Resources).Append("\n");
            sb.Append("  SecurityContext: ").Append(SecurityContext).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  Stdin: ").Append(Stdin).Append("\n");
            sb.Append("  StdinOnce: ").Append(StdinOnce).Append("\n");
            sb.Append("  TerminationMessagePath: ").Append(TerminationMessagePath).Append("\n");
            sb.Append("  TerminationMessagePolicy: ").Append(TerminationMessagePolicy).Append("\n");
            sb.Append("  Tty: ").Append(Tty).Append("\n");
            sb.Append("  VolumeDevices: ").Append(VolumeDevices).Append("\n");
            sb.Append("  VolumeMounts: ").Append(VolumeMounts).Append("\n");
            sb.Append("  WorkingDir: ").Append(WorkingDir).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ArgoScriptTemplate);
        }

        /// <summary>
        /// Returns true if ArgoScriptTemplate instances are equal
        /// </summary>
        /// <param name="input">Instance of ArgoScriptTemplate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ArgoScriptTemplate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Args == input.Args ||
                    this.Args != null &&
                    this.Args.SequenceEqual(input.Args)
                ) && 
                (
                    this.Command == input.Command ||
                    this.Command != null &&
                    this.Command.SequenceEqual(input.Command)
                ) && 
                (
                    this.Env == input.Env ||
                    this.Env != null &&
                    this.Env.SequenceEqual(input.Env)
                ) && 
                (
                    this.EnvFrom == input.EnvFrom ||
                    this.EnvFrom != null &&
                    this.EnvFrom.SequenceEqual(input.EnvFrom)
                ) && 
                (
                    this.Image == input.Image ||
                    (this.Image != null &&
                    this.Image.Equals(input.Image))
                ) && 
                (
                    this.ImagePullPolicy == input.ImagePullPolicy ||
                    (this.ImagePullPolicy != null &&
                    this.ImagePullPolicy.Equals(input.ImagePullPolicy))
                ) && 
                (
                    this.Lifecycle == input.Lifecycle ||
                    (this.Lifecycle != null &&
                    this.Lifecycle.Equals(input.Lifecycle))
                ) && 
                (
                    this.LivenessProbe == input.LivenessProbe ||
                    (this.LivenessProbe != null &&
                    this.LivenessProbe.Equals(input.LivenessProbe))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Ports == input.Ports ||
                    this.Ports != null &&
                    this.Ports.SequenceEqual(input.Ports)
                ) && 
                (
                    this.ReadinessProbe == input.ReadinessProbe ||
                    (this.ReadinessProbe != null &&
                    this.ReadinessProbe.Equals(input.ReadinessProbe))
                ) && 
                (
                    this.Resources == input.Resources ||
                    (this.Resources != null &&
                    this.Resources.Equals(input.Resources))
                ) && 
                (
                    this.SecurityContext == input.SecurityContext ||
                    (this.SecurityContext != null &&
                    this.SecurityContext.Equals(input.SecurityContext))
                ) && 
                (
                    this.Source == input.Source ||
                    (this.Source != null &&
                    this.Source.Equals(input.Source))
                ) && 
                (
                    this.Stdin == input.Stdin ||
                    (this.Stdin != null &&
                    this.Stdin.Equals(input.Stdin))
                ) && 
                (
                    this.StdinOnce == input.StdinOnce ||
                    (this.StdinOnce != null &&
                    this.StdinOnce.Equals(input.StdinOnce))
                ) && 
                (
                    this.TerminationMessagePath == input.TerminationMessagePath ||
                    (this.TerminationMessagePath != null &&
                    this.TerminationMessagePath.Equals(input.TerminationMessagePath))
                ) && 
                (
                    this.TerminationMessagePolicy == input.TerminationMessagePolicy ||
                    (this.TerminationMessagePolicy != null &&
                    this.TerminationMessagePolicy.Equals(input.TerminationMessagePolicy))
                ) && 
                (
                    this.Tty == input.Tty ||
                    (this.Tty != null &&
                    this.Tty.Equals(input.Tty))
                ) && 
                (
                    this.VolumeDevices == input.VolumeDevices ||
                    this.VolumeDevices != null &&
                    this.VolumeDevices.SequenceEqual(input.VolumeDevices)
                ) && 
                (
                    this.VolumeMounts == input.VolumeMounts ||
                    this.VolumeMounts != null &&
                    this.VolumeMounts.SequenceEqual(input.VolumeMounts)
                ) && 
                (
                    this.WorkingDir == input.WorkingDir ||
                    (this.WorkingDir != null &&
                    this.WorkingDir.Equals(input.WorkingDir))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Args != null)
                    hashCode = hashCode * 59 + this.Args.GetHashCode();
                if (this.Command != null)
                    hashCode = hashCode * 59 + this.Command.GetHashCode();
                if (this.Env != null)
                    hashCode = hashCode * 59 + this.Env.GetHashCode();
                if (this.EnvFrom != null)
                    hashCode = hashCode * 59 + this.EnvFrom.GetHashCode();
                if (this.Image != null)
                    hashCode = hashCode * 59 + this.Image.GetHashCode();
                if (this.ImagePullPolicy != null)
                    hashCode = hashCode * 59 + this.ImagePullPolicy.GetHashCode();
                if (this.Lifecycle != null)
                    hashCode = hashCode * 59 + this.Lifecycle.GetHashCode();
                if (this.LivenessProbe != null)
                    hashCode = hashCode * 59 + this.LivenessProbe.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Ports != null)
                    hashCode = hashCode * 59 + this.Ports.GetHashCode();
                if (this.ReadinessProbe != null)
                    hashCode = hashCode * 59 + this.ReadinessProbe.GetHashCode();
                if (this.Resources != null)
                    hashCode = hashCode * 59 + this.Resources.GetHashCode();
                if (this.SecurityContext != null)
                    hashCode = hashCode * 59 + this.SecurityContext.GetHashCode();
                if (this.Source != null)
                    hashCode = hashCode * 59 + this.Source.GetHashCode();
                if (this.Stdin != null)
                    hashCode = hashCode * 59 + this.Stdin.GetHashCode();
                if (this.StdinOnce != null)
                    hashCode = hashCode * 59 + this.StdinOnce.GetHashCode();
                if (this.TerminationMessagePath != null)
                    hashCode = hashCode * 59 + this.TerminationMessagePath.GetHashCode();
                if (this.TerminationMessagePolicy != null)
                    hashCode = hashCode * 59 + this.TerminationMessagePolicy.GetHashCode();
                if (this.Tty != null)
                    hashCode = hashCode * 59 + this.Tty.GetHashCode();
                if (this.VolumeDevices != null)
                    hashCode = hashCode * 59 + this.VolumeDevices.GetHashCode();
                if (this.VolumeMounts != null)
                    hashCode = hashCode * 59 + this.VolumeMounts.GetHashCode();
                if (this.WorkingDir != null)
                    hashCode = hashCode * 59 + this.WorkingDir.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
