apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shipbot.fullname" . }}
  labels:
{{ include "shipbot.labels" . | indent 4 }}
data:
  appsettings.Production.json: {{ tpl ( .Files.Get "files/appsettings.production.json" ) . | b64enc }}
type: Opaque