issuer: http://localhost:5556

storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db
    
web:
  http: 0.0.0.0:5556  
  
connectors: []
#  - type: github
#    id: github
#    name: GitHub
#    config:
#      clientID: $GITHUB_CLIENT_ID
#      clientSecret: $GITHUB_CLIENT_SECRET
#      redirectURI: https://dex.example.com:32000/callback
#      org: kubernetes
oauth2:
  responseTypes: [ "code", "token", "id_token" ]
  skipApprovalScreen: true
  alwaysShowLoginScreen: false
  passwordConnector: local
      
staticClients:
  - id: example-app
    redirectURIs:
      - 'http://localhost:5000/signin-oidc'
    name: 'Example App'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
  - id: postman
    redirectURIs:
      - 'https://oauth.pstmn.io/v1/callback'
    name: "Postman"
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0

enablePasswordDB: true

staticPasswords:
  - email: "admin@example.com"
    # bcrypt hash of the string "password"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"