// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shipbot.Controller.Core.Deployments;

namespace Shipbot.DbMigrations.Migrations.DeploymentsDb
{
    [DbContext(typeof(DeploymentsDbContext))]
    partial class DeploymentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Shipbot.Controller.Core.Deployments.Dao.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CurrentImageTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeploymentDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageRepository")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAutomaticDeployment")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetImageTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "ImageRepository", "UpdatePath", "CurrentImageTag", "TargetImageTag")
                        .IsUnique();

                    b.ToTable("deployments");
                });
#pragma warning restore 612, 618
        }
    }
}
