name: Build and Push Latest Image

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Docker repository to tag the image with
          repository: georgevella/shipbot
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          tags: latest-dev
          # Automatically tags the built image with the git reference as per the readme
          tag_with_ref: true
          # Automatically tags the built image with the git short SHA as per the readme
          tag_with_sha: true
          # Path to the build context
          path: ./src
          # Path to the Dockerfile (Default is '{path}/Dockerfile')
          dockerfile: ./src/Shipbot.Controller/Dockerfile
          # build_args: 
          # labels: 
          add_git_labels: true
          push: true
